GET http://localhost:8080/calculate?operand1=10&operator=+&operand2=45
Accept: application/json

###
GET http://localhost:8080/calculate?operand1=10&operator=-&operand2=45
Accept: application/json

###
GET http://localhost:8080/calculate?operand1=10&operator=*&operand2=45
Accept: application/json

###
 GET http://localhost:8080/calculate?operand1=10&operator=/&operand2=45
